### ISSUE TITLE
Usage of sync.Map

### ISSUE THREAD

**Issue by PumpkinSeed** [antoniomo/shardedmap#1]
What about to use sync.Map instead of the following pattern:
```
mutexes    []sync.RWMutex
maps       []map[uint64]interface{}
```

Mostly your package would be a wrapper around with the necessary checks, but much more efficient because of the built-in concurrent-safe map.

**Comment by antoniomo** [comment]
Hi,

The whole point is to not use `sync.Map` :) Not only `sync.Map` is already concurrent so it doesn't need extra checks in that sense, but if you have a balanced amount of writes and not just a read-mostly usage, `sync.Map` won't perform very well. Check the `README.md` for more tips :)
